// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.bs.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var $$Response = {};

function get(url) {
  return $$Promise.$$catch(fetch(url, undefined).then(function (res) {
                    return res.json();
                  }).then(function (data) {
                  return Promise.resolve({
                              TAG: /* Ok */0,
                              _0: data.code
                            });
                }), (function (e) {
                var msg;
                if (e.RE_EXN_ID === $$Promise.JsError) {
                  var msg$1 = e._1.message;
                  msg = msg$1 !== undefined ? msg$1 : "";
                } else {
                  msg = "Unexpected error occurred";
                }
                return Promise.resolve({
                            TAG: /* Error */1,
                            _0: msg
                          });
              }));
}

var API = {
  get: get
};

var FailedRequest = /* @__PURE__ */Caml_exceptions.create("App-App.FailedRequest");

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCode = match[1];
  React.useEffect((function () {
          get("http://localhost:8080/").then(function (ret) {
                if (ret.TAG !== /* Ok */0) {
                  return Promise.reject({
                              RE_EXN_ID: FailedRequest,
                              _1: "Error: " + ret._0
                            });
                }
                var code = ret._0;
                return Promise.resolve(Curry._1(setCode, (function (param) {
                                  return code;
                                })));
              });
          
        }), []);
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "bg-blue-200 w-screen h-16"
                }, React.createElement("p", {
                      className: ""
                    }, match[0])));
}

var make = App;

export {
  $$Response ,
  API ,
  FailedRequest ,
  make ,
  
}
/* react Not a pure module */
