// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.bs.js";

var WalletResponse = {};

function MakeGet(Res) {
  var get = function (url) {
    return $$Promise.$$catch(fetch(url, undefined).then(function (res) {
                      return res.json();
                    }).then(function (data) {
                    return Promise.resolve({
                                TAG: /* Ok */0,
                                _0: [
                                  data.usd_bal,
                                  data.btc_bal,
                                  data.msg
                                ]
                              });
                  }), (function (e) {
                  var msg;
                  if (e.RE_EXN_ID === $$Promise.JsError) {
                    var msg$1 = e._1.message;
                    msg = msg$1 !== undefined ? msg$1 : "";
                  } else {
                    msg = "Unexpected error occurred";
                  }
                  return Promise.resolve({
                              TAG: /* Error */1,
                              _0: msg
                            });
                }));
  };
  return {
          get: get
        };
}

export {
  WalletResponse ,
  MakeGet ,
  
}
/* No side effect */
